name: "ESC/POS Receipt Printer"
slug: "receipt_escpos_printer"
version: "1.0.2"
description: "Home Assistant add-on to print shopping lists via ESC/POS network printer"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
options:
  printer_ip: "192.168.1.79"
  printer_port: 9100
schema:
  printer_ip: str
  printer_port: int
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
