name: "ESC/POS Receipt Printer"
slug: "receipt_escpos_printer"
version: "1.0.9"
description: "Home Assistant add-on to print shopping lists via ESC/POS network printer"
arch:
  - amd64
  - aarch64
  - armv7
startup: once
init: "false"
boot: manual
options:
  printer_ip: "192.168.1.79"
  printer_port: 9100
  ha_url: "http://homeassistant:8123"
  ha_token: "your_long_lived_token"
schema:
  printer_ip: str
  printer_port: int
  ha_url: str
  ha_token: str
build: "true"
